[theme]
base="dark"
primaryColor="#ffffff"
backgroundColor="#000000"
secondaryBackgroundColor="#350030"
textColor="#ffffff"
font="sans serif"
linkColor="violet"
codeBackgroundColor="#000000"
baseRadius = "0.5rem"
showWidgetBorder = true
# baseFontSize = 20


